module GHCJS.DOM.Navigator where

data Navigator = Navigator
class IsNavigator a
instance IsNavigator Navigator

ghcjs_dom_navigator_java_enabled = undefined
navigatorJavaEnabled = undefined
ghcjs_dom_navigator_get_storage_updates = undefined
navigatorGetStorageUpdates = undefined
ghcjs_dom_navigator_get_app_code_name = undefined
navigatorGetAppCodeName = undefined
ghcjs_dom_navigator_get_app_name = undefined
navigatorGetAppName = undefined
ghcjs_dom_navigator_get_app_version = undefined
navigatorGetAppVersion = undefined
ghcjs_dom_navigator_get_language = undefined
navigatorGetLanguage = undefined
ghcjs_dom_navigator_get_user_agent = undefined
navigatorGetUserAgent = undefined
ghcjs_dom_navigator_get_platform = undefined
navigatorGetPlatform = undefined
ghcjs_dom_navigator_get_plugins = undefined
navigatorGetPlugins = undefined
ghcjs_dom_navigator_get_mime_types = undefined
navigatorGetMimeTypes = undefined
ghcjs_dom_navigator_get_product = undefined
navigatorGetProduct = undefined
ghcjs_dom_navigator_get_product_sub = undefined
navigatorGetProductSub = undefined
ghcjs_dom_navigator_get_vendor = undefined
navigatorGetVendor = undefined
ghcjs_dom_navigator_get_vendor_sub = undefined
navigatorGetVendorSub = undefined
ghcjs_dom_navigator_get_cookie_enabled = undefined
navigatorGetCookieEnabled = undefined
ghcjs_dom_navigator_get_on_line = undefined
navigatorGetOnLine = undefined
castToNavigator = undefined
gTypeNavigator = undefined
toNavigator = undefined
